Task 1 2
19214KseniaLyashcsenko/OOP pull request #3
Opened 2020-11-12 02:51 UTC by 19214KseniaLyashcsenko

2020-11-12 14:27 UTC, vlitomsk requested changes
Замечания нужно исправить, на вопросы ответить %)

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +    static int k = 0;
При повторном вызове метода поиска эти поля будут уже иметь не изначальные свои значения, возвращенное методом поиска значение от этого будет неверным.
Непонятно, зачем вообще их вынесли в поля класса, а не использовали локальные переменные функции.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +    }
Всё, можно расслабиться ;-) -- стандартные коллекции в этом задании использовать можно.
В java есть удобные динамические массивы, например java.util.ArrayList<T>. При их использовании необходимость в таких приседаниях с перевыделением памяти отпадает.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +    }
Предлагаю на него переделать.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +    public static long[] substringSearch(InputStream inStream, String substrIn) throws IOException {
Добавь валидацию параметров метода.
inStream не должен быть null-ом, substrIn не может быть null-ом или пустой строкой.
В случае несоответствия выбрасывай ошибку IllegalArgumentException.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +    public static long[] substringSearch(InputStream inStream, String substrIn) throws IOException {
На этапе проверки предусловий, бывает, отлавливается часть ошибок в программе.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +        char str[] = new char[substr.length * 3];
Что за магические константы 3, 2?
Если одну из них поменять, программа нормально будет работать?
Предлагаю сделать так, чтобы только в одном месте менять приходилось.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +        char substr[] = new char[substrIn.length()];
Память здесь выделять не нужно, это сделает toCharArray() и вернет указатель на выделенную область.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +        long pos = 0;
Не говорящие имена переменных. k1, k2, pos -- это что? Приходится из контекста, где они применяются, додумывать.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +                str[substr.length * 2 + k2] = 0;
А это для чего сделано?

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/main/java/SubstringSearch.java
> +        BufferedReader readIn = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
Хорошее правило: используешь новый класс -- смотри в документации или в среде разработки, не реализует ли он AutoClosable. Если реализует, то однозначно нужно использовать try-with-resources. Если таких классов несколько в одном выражении, то придется разбивать:
try (var isr = new InputStreamReader(...))
try (var br = new BufferedReader(isr)) {
  ...
}

В других местах тоже это проверь и исправь.

2020-11-12 14:27 UTC, vlitomsk commented on Task_1_2/src/test/java/Test3.java
> +public class Test3{
Почему тесты разбили на несколько классов?

2020-11-13 09:31 UTC, 19214KseniaLyashcsenko commented on Task_1_2/src/main/java/SubstringSearch.java
> +        char str[] = new char[substr.length * 3];
Ну у меня массив str размера как три подстроки, потому что в начале этого массива лежит сама подстрока, а в оставшуюся часть, размера как две подстроки, записывается часть введенной строки, и в этой оставшейся части уже сдвигается все и добавляется новая часть строки. Просто мы же не знаем как велика может быть подстрока, поэтому я считаю все в размере подстроки)

2020-11-19 19:20 UTC, vlitomsk approved these changes
ок принято

2020-11-19 19:21 UTC, merged