Task 3 2
19214KseniaLyashcsenko/OOP pull request #5
Opened 2020-12-07 10:35 UTC by 19214KseniaLyashcsenko

2020-12-11 05:24 UTC, vlitomsk requested changes
req

2020-12-11 05:24 UTC, vlitomsk commented on Task_3_2/src/main/java/RecordBook.java
> +
Надо выставить модификаторы доступа

2020-12-11 05:24 UTC, vlitomsk commented on Task_3_2/src/main/java/RecordBook.java
> +    static boolean[] isFiveInSem = new boolean[]{true,true,true,true,true,true,true,true,true};
Предлагаю в качестве номера семестра использовать тип int.
Потому что пользователю класса будет сложно угадать нужную строчку, да и зачем от него требовать лишнее -- печатать слово "Semester"?

2020-12-11 05:24 UTC, vlitomsk commented on Task_3_2/src/main/java/RecordBook.java
> +
Как создать несколько экземпляров зачетной книжки для нескольких студентов?
static этому мешает.

2020-12-11 05:24 UTC, vlitomsk commented on Task_3_2/src/main/java/RecordBook.java
> +        if(((float)counterFive/counter * 100 >=75) && arrGrades.get(semester[8] - 1) == 5 && isThree == false) return true;
Константы предлагаю назвать -- 8 семестр (последний), и пороговые 75%.

2020-12-11 05:24 UTC, vlitomsk commented on Task_3_2/src/main/java/RecordBook.java
> +    private static ArrayList<Integer> arrGrades = new ArrayList<Integer>(Collections.nCopies(100, 0));
Откуда взялось число 100?

2020-12-13 10:51 UTC, 19214KseniaLyashcsenko commented on Task_3_2/src/main/java/RecordBook.java
> +    private static ArrayList<Integer> arrGrades = new ArrayList<Integer>(Collections.nCopies(100, 0));
А у меня для хранения всех оценок один массив, и я первоначально заполняю его нулями, так как оценки за семестр могут добавляться не по порядку, а  100 - просто для верности

2020-12-14 09:42 UTC, vlitomsk commented on Task_3_2/src/main/java/RecordBook.java
> +    private static ArrayList<Integer> arrGrades = new ArrayList<Integer>(Collections.nCopies(100, 0));
А если через 20 лет использования программы появится новый 101-ый предмет, оценку по которому нужно внести в зачетную книжку, нужно будет переписывать программу?

2020-12-15 06:07 UTC, vlitomsk requested changes
Предлагаю добавить универсальности в код лабораторной.

2020-12-15 06:07 UTC, vlitomsk commented on Task_3_2/src/main/java/RecordBook.java
> +        int eightSem = 8;
Как сделать зачетную книжку для специалистов ФЕНа или магистрантов ФИТ? У них курс обучения не из 8 семестров состоит.

2021-01-17 09:54 UTC, vlitomsk approved these changes
принято!

2021-01-17 09:55 UTC, merged